### ISSUE TITLE
metadata.html.twig

### ISSUE THREAD

**Issue by mab-plus** [MarcelKr/grav-theme-tail#17]
Hello

where is this file metadata.html.twig ?

we can read in  base.html.twig    

{% include 'partials/metadata.html.twig' %}

@+

**Comment by MarcelKr** [comment]
It's a file which get's automatically included from the grav system. It's not part of this theme. It automatically gets populated by the stuff you add in your configuration: https://learn.getgrav.org/17/admin-panel/dashboard/configuration-site#metadata
