### ISSUE TITLE
unsure whats the logic behind this

### ISSUE THREAD

**Issue by diomed** [MarcelKr/grav-theme-tail#19]
Instead of having

            `<a href="{{ home_url }}">{{ site.title }}</a>`

you put 

            `<a href="{{ home_url }}">{{ site.author.name }}</a>`

this works for your site, I guess, but not really for others.

I mean, I'm unsure what stops you from renaming your site title to your own name.
That would be simpler than other people having to change code or having site name as site.author.name which makes little sense.

**Comment by MarcelKr** [comment]
No logic behind that, just an oversight. Fixed with [v1.5.1](https://github.com/MarcelKr/grav-theme-tail/releases/tag/1.5.1)
